// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PLTour.Admin.Models.DbContext;

#nullable disable

namespace PLTour.Admin.Migrations
{
    [DbContext(typeof(PLTourDbContext))]
    partial class PLTourDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PLTour.Admin.Models.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Các quán ăn vỉa hè, đồ ăn đường phố đặc sắc",
                            DisplayOrder = 1,
                            Icon = "fa-utensils",
                            IsActive = true,
                            Name = "Ẩm thực đường phố"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Nhà hàng, quán ăn cao cấp",
                            DisplayOrder = 2,
                            Icon = "fa-restaurant",
                            IsActive = true,
                            Name = "Nhà hàng"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Các quán cà phê, trà sữa, đồ uống",
                            DisplayOrder = 3,
                            Icon = "fa-coffee",
                            IsActive = true,
                            Name = "Quán cà phê"
                        },
                        new
                        {
                            CategoryId = 4,
                            Description = "Các điểm tham quan, du lịch trong khu vực",
                            DisplayOrder = 4,
                            Icon = "fa-camera",
                            IsActive = true,
                            Name = "Điểm tham quan"
                        },
                        new
                        {
                            CategoryId = 5,
                            Description = "Các sự kiện, lễ hội ẩm thực",
                            DisplayOrder = 5,
                            Icon = "fa-calendar",
                            IsActive = true,
                            Name = "Sự kiện"
                        });
                });

            modelBuilder.Entity("PLTour.Admin.Models.Entities.Language", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LanguageId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("FlagIcon")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LanguageId");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            LanguageId = 1,
                            Code = "vi",
                            CreatedDate = new DateTime(2026, 3, 20, 1, 41, 27, 284, DateTimeKind.Local).AddTicks(5661),
                            DisplayOrder = 1,
                            FlagIcon = "flag-icon-vn",
                            IsActive = true,
                            Name = "Tiếng Việt"
                        },
                        new
                        {
                            LanguageId = 2,
                            Code = "en",
                            CreatedDate = new DateTime(2026, 3, 20, 1, 41, 27, 284, DateTimeKind.Local).AddTicks(5680),
                            DisplayOrder = 2,
                            FlagIcon = "flag-icon-us",
                            IsActive = true,
                            Name = "English"
                        },
                        new
                        {
                            LanguageId = 3,
                            Code = "zh",
                            CreatedDate = new DateTime(2026, 3, 20, 1, 41, 27, 284, DateTimeKind.Local).AddTicks(5682),
                            DisplayOrder = 3,
                            FlagIcon = "flag-icon-cn",
                            IsActive = true,
                            Name = "中文"
                        },
                        new
                        {
                            LanguageId = 4,
                            Code = "ko",
                            CreatedDate = new DateTime(2026, 3, 20, 1, 41, 27, 284, DateTimeKind.Local).AddTicks(5683),
                            DisplayOrder = 4,
                            FlagIcon = "flag-icon-kr",
                            IsActive = true,
                            Name = "한국어"
                        },
                        new
                        {
                            LanguageId = 5,
                            Code = "ja",
                            CreatedDate = new DateTime(2026, 3, 20, 1, 41, 27, 284, DateTimeKind.Local).AddTicks(5686),
                            DisplayOrder = 5,
                            FlagIcon = "flag-icon-jp",
                            IsActive = true,
                            Name = "日本語"
                        });
                });

            modelBuilder.Entity("PLTour.Admin.Models.Entities.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("LocationId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("PLTour.Admin.Models.Entities.Narration", b =>
                {
                    b.Property<int>("NarrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NarrationId"));

                    b.Property<string>("AudioUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<int>("LanguageId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("NarrationId");

                    b.HasIndex("LanguageId");

                    b.HasIndex("LocationId", "IsDefault")
                        .IsUnique()
                        .HasFilter("IsDefault = 1");

                    b.ToTable("Narrations");
                });

            modelBuilder.Entity("PLTour.Admin.Models.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VendorId")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("VendorId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("PLTour.Admin.Models.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedDate = new DateTime(2026, 3, 20, 1, 41, 27, 389, DateTimeKind.Local).AddTicks(8646),
                            Email = "admin@pltour.com",
                            FullName = "Administrator",
                            IsActive = true,
                            PasswordHash = "$2a$11$5fKNOKWZyLIhXxKe0AL.T.f5Y2BpiBriVlWaXr6.qvA9UGKAxjg5u",
                            Phone = "0123456789",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("PLTour.Admin.Models.Entities.Vendor", b =>
                {
                    b.Property<int>("VendorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VendorId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShopName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VendorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("PLTour.Admin.Models.Entities.Location", b =>
                {
                    b.HasOne("PLTour.Admin.Models.Entities.Category", "Category")
                        .WithMany("Locations")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PLTour.Admin.Models.Entities.Narration", b =>
                {
                    b.HasOne("PLTour.Admin.Models.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("LanguageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PLTour.Admin.Models.Entities.Location", "Location")
                        .WithMany("Narrations")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Language");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("PLTour.Admin.Models.Entities.Product", b =>
                {
                    b.HasOne("PLTour.Admin.Models.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PLTour.Admin.Models.Entities.Vendor", "Vendor")
                        .WithMany("Products")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("PLTour.Admin.Models.Entities.Vendor", b =>
                {
                    b.HasOne("PLTour.Admin.Models.Entities.Category", "Category")
                        .WithMany("Vendors")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("PLTour.Admin.Models.Entities.Category", b =>
                {
                    b.Navigation("Locations");

                    b.Navigation("Vendors");
                });

            modelBuilder.Entity("PLTour.Admin.Models.Entities.Location", b =>
                {
                    b.Navigation("Narrations");
                });

            modelBuilder.Entity("PLTour.Admin.Models.Entities.Vendor", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
