using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace PLTour.API.Migrations
{
    /// <inheritdoc />
    public partial class AddVendorStores : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("CREATE TABLE IF NOT EXISTS \"VendorStores\" (\n    \"StoreId\" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    \"VendorId\" integer NOT NULL,\n    \"StoreName\" character varying(200) NOT NULL,\n    \"Description\" character varying(1000),\n    \"LogoUrl\" character varying(500),\n    \"Address\" character varying(500),\n    \"Latitude\" double precision,\n    \"Longitude\" double precision,\n    \"Plan\" character varying(30) NOT NULL DEFAULT 'Free',\n    \"PlanExpiresAt\" timestamp without time zone,\n    \"IsDefault\" boolean NOT NULL DEFAULT false,\n    \"IsActive\" boolean NOT NULL DEFAULT true,\n    \"CreatedDate\" timestamp without time zone NOT NULL DEFAULT NOW(),\n    \"UpdatedDate\" timestamp without time zone NULL,\n    CONSTRAINT \"FK_VendorStores_Vendors_VendorId\" FOREIGN KEY (\"VendorId\") REFERENCES \"Vendors\" (\"VendorId\") ON DELETE CASCADE\n);");

            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_VendorStores_VendorId\" ON \"VendorStores\" (\"VendorId\");");

            migrationBuilder.Sql("CREATE TABLE IF NOT EXISTS \"VendorSubscriptionTransactions\" (\n    \"TransactionId\" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,\n    \"VendorId\" integer NOT NULL,\n    \"PlanCode\" character varying(30) NOT NULL,\n    \"Amount\" numeric NOT NULL,\n    \"Currency\" character varying(100) NOT NULL,\n    \"Status\" character varying(50) NOT NULL,\n    \"PaymentMethod\" character varying(100),\n    \"OrderId\" character varying(100),\n    \"TransactionNo\" character varying(100),\n    \"CreatedAt\" timestamp without time zone NOT NULL,\n    \"PaidAt\" timestamp without time zone,\n    \"ExpiresAt\" timestamp without time zone,\n    \"RawResponse\" character varying(2000),\n    CONSTRAINT \"FK_VendorSubscriptionTransactions_Vendors_VendorId\" FOREIGN KEY (\"VendorId\") REFERENCES \"Vendors\" (\"VendorId\") ON DELETE CASCADE\n);");

            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_VendorSubscriptionTransactions_VendorId\" ON \"VendorSubscriptionTransactions\" (\"VendorId\");");

            migrationBuilder.Sql("ALTER TABLE IF EXISTS \"Products\" ADD COLUMN IF NOT EXISTS \"StoreId\" integer;");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_Products_StoreId\" ON \"Products\" (\"StoreId\");");
            migrationBuilder.Sql("DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'FK_Products_VendorStores_StoreId') THEN ALTER TABLE \"Products\" ADD CONSTRAINT \"FK_Products_VendorStores_StoreId\" FOREIGN KEY (\"StoreId\") REFERENCES \"VendorStores\" (\"StoreId\") ON DELETE SET NULL; END IF; END $$;");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"VendorSubscriptionTransactions\";");
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"VendorStores\";");
        }
    }
}
